---
- hosts: ios            # 対象のグループ名（インベントリファイル内の定義）
  gather_facts: false   # システム情報収集機能の無効化（時間短縮のため）

  # ここからタスクの定義
  tasks:
    # タスク1: インターフェースへdescriptionの設定
    - name: config interface description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet3
            description: changed_by_ansible
  